## 문자열 압축

In [14]:
#input
s = "ababcdcdababcdcd"

In [2]:
from queue import deque
def solution(s):
    result = []
    #총 몇개 단위로 자를 건지는 len(s)의 반만 계산하면 되지만, 길이가 1인경우를 고려하여 +2로 해준다
    steps = [_ for _ in range(1, len(s)//2+2)]
    #하나씩 자르면서 쪼갠 것을 각각 queue array에 담는다
    for step in steps:
        array = deque()
        for i in range(0,len(s),step):
            array.append(s[i:i+step])
        compressed_string = ''
        #array를 하나씩 팝하는데, 다음에 같은 녀석이 나오면 count를 해준다
        while array:
            count = 1
            popped = array.popleft()
            for j in range(len(array)):
                if popped != array[j]:
                    break
                else:
                    count += 1
            #count가 1이면 굳이 string에 더할 필요가없고
            if count == 1:
                compressed_string += popped
            #아니면 count와 같이 더한다
            else:
                compressed_string += str(count) + popped
            #자기 자신을 제외하고 지워야하는 원소들을 차례로 지운다
            to_remove = count - 1
            while to_remove != 0:
                array.popleft()
                to_remove -= 1
        # 해당 압축된 문자열의 길이를 result에 담고
        result.append(len(compressed_string))
    #그 값이가장 적은 것을 출력한다
    return min(result)

In [3]:
solution(s)

9

## 괄호 변환

In [4]:
#input
p = "(()())()"

In [5]:
def divide(p):
    open_parenthesis = 0
    close_parenthesis = 0
    
    for i in range(len(p)):
        if p[i] == '(':
            open_parenthesis += 1
        else:
            close_parenthesis += 1
            
        if open_parenthesis == close_parenthesis:
            return p[:i+1], p[i+1:]

def is_balanced(u):
    #괄호가 갖춰져있으면 모두 없앤다. 
    while u != '':
        if '()' in u:
            u = u.replace('()','')
        else:
            break
    # 다 없어지면 true 아니면 false
    if u == '':
        return True
    else:
        return False

def solution(p):
    #Step 1
    if not p:
        return ""
    
    #Step 2
    u, v = divide(p)
    
    #Step 3 - 여기서 재귀함수가 핵심
    if is_balanced(u):
        return u + solution(v)
    else:
        # Step 4-1
        answer = '('
        # Step 4-2
        answer += solution(v)
        # Step 4-3
        answer += ')'
        # Step 4-4
        for i in u[1:len(u)-1]:
            if i == '(':
                answer += ')'
            else:
                answer += '('
        
        # Step 4-5
        return answer

In [6]:
solution(p)

'(()())()'

## 자물쇠와 열쇠

In [1]:
#input
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]

In [6]:
#numpy를 사용했을 때 rotate와 move가 훨씬 편리하다

import numpy as np
def solution(key,lock):
    key = np.array(key)
    # key 와 lock을 결합시킨 matrix를 만들고 lock을 중앙에 놓는다 --> lock_matrix
    lock_matrix = np.zeros([len(lock)+len(key)*2-2,len(lock)+len(key)*2-2], dtype = int)
    lock_matrix[len(key)-1:len(key)-1+len(lock),len(key)-1:len(key)-1+len(lock)] = np.array(lock)
    for i in range(0,4):
        #각각을 90도로 네번 돌린 key를 왼쪽위 모서리로 하는 matrix를 만든다 -->key_matrix
        rotated_key = np.rot90(key,i)
        key_matrix = np.zeros([len(lock)+len(key)*2-2,len(lock)+len(key)*2-2], dtype = int)
        key_matrix[0:len(key),0:len(key)] = rotated_key
        #j는 오른쪽으로 이동, k는 왼쪽으로 이동. matrix 끝까지 옮긴다
        for j in range(len(key_matrix)-len(key)+1):
            for k in range(len(key_matrix)-len(key)+1):
                new_matrix = np.roll(key_matrix,j,axis=1)
                new_matrix = np.roll(new_matrix,k,axis=0)
                #옮겨진 matrix를 new로 놓고 lock_matrix랑 Element by element로 결합
                result = new_matrix + lock_matrix
                #중앙만 따로 뗀다
                result = result[len(key)-1:len(key)-1+len(lock),len(key)-1:len(key)-1+len(lock)]
                #1로 채워져있는 같은 사이즈의 answer matrix를 만들고
                answer = np.ones([len(lock),len(lock)], dtype = int)
                # result와 answer의 모든 원소가 같으면 True 아니면 계속 진행
                if np.all(answer == result):
                    return True
                else:
                    continue
    #하나도 없으면 False 반환
    return False

In [7]:
solution(key,lock)

[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[1 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


True

## 가사검색

In [10]:
# inputs
words = ["frodo", "front", "frost", "frozen", "frame", "kakao"]
queries = ["fro??", "????o", "fr???", "fro???", "pro?"]

In [11]:
class Node(object): ## Trie Node 구성
    def __init__(self, key):
        self.key = key ## 시작값(이전의 값 개념)
        self.remain_length = {} ## Terminal까지 남아있는 문자열의 길이
        self.children = {} ## 자식


class Trie(object):
    def __init__(self):
        self.head = Node(None)

    def insert(self, string):
        ## key에는 문자, length에는 남아있는 string의 길이를 담았음
        curr_node = self.head
    
        #초기 세팅
        remain_length = len(string)
        if remain_length in curr_node.remain_length:
            curr_node.remain_length[remain_length] += 1
        else:
            curr_node.remain_length[remain_length] = 1
        
        #문자하나씩 돌면서 진행
        for char in string:
            if char not in curr_node.children:
                curr_node.children[char] = Node(char)

            curr_node = curr_node.children[char]
            remain_length -= 1
            
            if remain_length in curr_node.remain_length:
                curr_node.remain_length[remain_length] += 1
            else:
                curr_node.remain_length[remain_length] = 1

    def search_count(self, string, check_length):
        curr_node = self.head
        ## 찾아야할 "?" 포함한 string의 길이가 없다면 return 0
        if check_length+len(string) not in curr_node.remain_length:
            return 0
        
        for char in string:
            ## 찾아야할 string이 없다면 return 0
            if char in curr_node.children:                
                curr_node = curr_node.children[char]
            else:
                return 0
        ## string은 존재하는데 check_length가 remain_length에 있는지 확인!
        if check_length in curr_node.remain_length:
            return curr_node.remain_length[check_length]
        else:
            return 0


def solution(words, queries):
    t = Trie()
    inv_t = Trie()
    for word in words:
        t.insert(word)
        inv_t.insert(word[-1::-1])

    answer = []
    for i in range(len(queries)):
        query = queries[i]
        if query[0] is '?':  # 시작이 '?'
            query = query[-1::-1]
            chars = query.replace("?", "")
            check_length = len(query)-len(chars)
            answer.append(inv_t.search_count(chars, check_length))
        else: # 시작이 알파벳
            chars = query.replace("?", "")
            check_length = len(query) - len(chars)
            answer.append(t.search_count(chars, check_length))

    return answer

In [12]:
solution(words, queries)

[3, 2, 4, 1, 0]

In [13]:
#다른 사람 풀이
