## 문자열 압축

In [14]:
#input
s = "ababcdcdababcdcd"

In [2]:
from queue import deque
def solution(s):
    result = []
    #총 몇개 단위로 자를 건지는 len(s)의 반만 계산하면 되지만, 길이가 1인경우를 고려하여 +2로 해준다
    steps = [_ for _ in range(1, len(s)//2+2)]
    #하나씩 자르면서 쪼갠 것을 각각 queue array에 담는다
    for step in steps:
        array = deque()
        for i in range(0,len(s),step):
            array.append(s[i:i+step])
        compressed_string = ''
        #array를 하나씩 팝하는데, 다음에 같은 녀석이 나오면 count를 해준다
        while array:
            count = 1
            popped = array.popleft()
            for j in range(len(array)):
                if popped != array[j]:
                    break
                else:
                    count += 1
            #count가 1이면 굳이 string에 더할 필요가없고
            if count == 1:
                compressed_string += popped
            #아니면 count와 같이 더한다
            else:
                compressed_string += str(count) + popped
            #자기 자신을 제외하고 지워야하는 원소들을 차례로 지운다
            to_remove = count - 1
            while to_remove != 0:
                array.popleft()
                to_remove -= 1
        # 해당 압축된 문자열의 길이를 result에 담고
        result.append(len(compressed_string))
    #그 값이가장 적은 것을 출력한다
    return min(result)

In [3]:
solution(s)

9

## 괄호 변환

In [4]:
#input
p = "(()())()"

In [5]:
def divide(p):
    open_parenthesis = 0
    close_parenthesis = 0
    
    for i in range(len(p)):
        if p[i] == '(':
            open_parenthesis += 1
        else:
            close_parenthesis += 1
            
        if open_parenthesis == close_parenthesis:
            return p[:i+1], p[i+1:]

def is_balanced(u):
    #괄호가 갖춰져있으면 모두 없앤다. 
    while u != '':
        if '()' in u:
            u = u.replace('()','')
        else:
            break
    # 다 없어지면 true 아니면 false
    if u == '':
        return True
    else:
        return False

def solution(p):
    #Step 1
    if not p:
        return ""
    
    #Step 2
    u, v = divide(p)
    
    #Step 3 - 여기서 재귀함수가 핵심
    if is_balanced(u):
        return u + solution(v)
    else:
        # Step 4-1
        answer = '('
        # Step 4-2
        answer += solution(v)
        # Step 4-3
        answer += ')'
        # Step 4-4
        for i in u[1:len(u)-1]:
            if i == '(':
                answer += ')'
            else:
                answer += '('
        
        # Step 4-5
        return answer

In [6]:
solution(p)

'(()())()'

## 자물쇠와 열쇠

In [1]:
#input
key = [[0, 0, 0], [1, 0, 0], [0, 1, 1]]
lock = [[1, 1, 1], [1, 1, 0], [1, 0, 1]]

In [6]:
#numpy를 사용했을 때 rotate와 move가 훨씬 편리하다

import numpy as np
def solution(key,lock):
    key = np.array(key)
    # key 와 lock을 결합시킨 matrix를 만들고 lock을 중앙에 놓는다 --> lock_matrix
    lock_matrix = np.zeros([len(lock)+len(key)*2-2,len(lock)+len(key)*2-2], dtype = int)
    lock_matrix[len(key)-1:len(key)-1+len(lock),len(key)-1:len(key)-1+len(lock)] = np.array(lock)
    for i in range(0,4):
        #각각을 90도로 네번 돌린 key를 왼쪽위 모서리로 하는 matrix를 만든다 -->key_matrix
        rotated_key = np.rot90(key,i)
        key_matrix = np.zeros([len(lock)+len(key)*2-2,len(lock)+len(key)*2-2], dtype = int)
        key_matrix[0:len(key),0:len(key)] = rotated_key
        #j는 오른쪽으로 이동, k는 왼쪽으로 이동. matrix 끝까지 옮긴다
        for j in range(len(key_matrix)-len(key)+1):
            for k in range(len(key_matrix)-len(key)+1):
                new_matrix = np.roll(key_matrix,j,axis=1)
                new_matrix = np.roll(new_matrix,k,axis=0)
                #옮겨진 matrix를 new로 놓고 lock_matrix랑 Element by element로 결합
                result = new_matrix + lock_matrix
                #중앙만 따로 뗀다
                result = result[len(key)-1:len(key)-1+len(lock),len(key)-1:len(key)-1+len(lock)]
                #1로 채워져있는 같은 사이즈의 answer matrix를 만들고
                answer = np.ones([len(lock),len(lock)], dtype = int)
                # result와 answer의 모든 원소가 같으면 True 아니면 계속 진행
                if np.all(answer == result):
                    return True
                else:
                    continue
    #하나도 없으면 False 반환
    return False

In [7]:
solution(key,lock)

[[0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[1 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


True

## 가사검색

In [10]:
# inputs
words = ["frodo", "front", "frost", "frozen", "frame", "kakao"]
queries = ["fro??", "????o", "fr???", "fro???", "pro?"]

In [11]:
class Node(object): ## Trie Node 구성
    def __init__(self, key):
        self.key = key ## 시작값(이전의 값 개념)
        self.remain_length = {} ## Terminal까지 남아있는 문자열의 길이
        self.children = {} ## 자식


class Trie(object):
    def __init__(self):
        self.head = Node(None)

    def insert(self, string):
        ## key에는 문자, length에는 남아있는 string의 길이를 담았음
        curr_node = self.head
    
        #초기 세팅
        remain_length = len(string)
        if remain_length in curr_node.remain_length:
            curr_node.remain_length[remain_length] += 1
        else:
            curr_node.remain_length[remain_length] = 1
        
        #문자하나씩 돌면서 진행
        for char in string:
            if char not in curr_node.children:
                curr_node.children[char] = Node(char)

            curr_node = curr_node.children[char]
            remain_length -= 1
            
            if remain_length in curr_node.remain_length:
                curr_node.remain_length[remain_length] += 1
            else:
                curr_node.remain_length[remain_length] = 1

    def search_count(self, string, check_length):
        curr_node = self.head
        ## 찾아야할 "?" 포함한 string의 길이가 없다면 return 0
        if check_length+len(string) not in curr_node.remain_length:
            return 0
        
        for char in string:
            ## 찾아야할 string이 없다면 return 0
            if char in curr_node.children:                
                curr_node = curr_node.children[char]
            else:
                return 0
        ## string은 존재하는데 check_length가 remain_length에 있는지 확인!
        if check_length in curr_node.remain_length:
            return curr_node.remain_length[check_length]
        else:
            return 0


def solution(words, queries):
    t = Trie()
    inv_t = Trie()
    for word in words:
        t.insert(word)
        inv_t.insert(word[-1::-1])

    answer = []
    for i in range(len(queries)):
        query = queries[i]
        if query[0] is '?':  # 시작이 '?'
            query = query[-1::-1]
            chars = query.replace("?", "")
            check_length = len(query)-len(chars)
            answer.append(inv_t.search_count(chars, check_length))
        else: # 시작이 알파벳
            chars = query.replace("?", "")
            check_length = len(query) - len(chars)
            answer.append(t.search_count(chars, check_length))

    return answer

In [12]:
solution(words, queries)

[3, 2, 4, 1, 0]

## 기둥과 보 설치

In [355]:
#input
n = 5
build_frame = [[0,0,0,1],[2,0,0,1],[4,0,0,1],[0,1,1,1],[1,1,1,1],[2,1,1,1],[3,1,1,1],[2,0,0,0],[1,1,1,0],[2,2,0,1]]

In [356]:
#추가가 가능한지 확인하는 함수
def check_available(x,y,a,array):
    if a == 0:
        if y == 0 or [x,y-1,0] in array or [x-1,y,1] in array or [x,y,1] in array:
            return True
        else:
            return False
    else:
        if ([x-1,y,1] in array and [x+1,y,1] in array) or [x,y-1,0] in array or [x+1,y-1,0] in array:
            return True
        else:
            return False

def solution(n,build_frame):
    answer = []
    for frame in build_frame:
        x,y,a,b = frame
        if b == 1 and check_available(x,y,a,answer):
            answer.append([x,y,a])
        elif b == 0 and [x,y,a] in answer:
            temp = answer[:]
            temp.remove([x,y,a])
            if temp:
                for element in temp:
                    x_1, y_1, a_1 = element
                    checked = check_available(x_1,y_1,a_1,temp)
                    if checked == False:
                        break
                if checked == True:
                    answer = temp
            else:
                answer = temp

    answer = sorted(answer, key = lambda x : (x[0], x[1], x[2]))
    return answer

In [358]:
solution(n,build_frame)

[[0, 0, 0], [0, 1, 1], [2, 1, 1], [3, 1, 1], [4, 0, 0]]

In [314]:
# 다른사람 풀이
def impossible(result):
    COL, ROW = 0, 1
    for x, y, a in result:
        if a == COL: # 기둥일 때
            if y != 0 and (x, y-1, COL) not in result and \
        (x-1, y, ROW) not in result and (x, y, ROW) not in result:
                return True
        else: # 보일 때
            if (x, y-1, COL) not in result and (x+1, y-1, COL) not in result and \
        not ((x-1, y, ROW) in result and (x+1, y, ROW) in result):
                return True
    return False

def solution(n, build_frame):
    result = set()

    for x, y, a, build in build_frame:
        item = (x, y, a)
        if build: # 추가일 때
            result.add(item)
            if impossible(result):
                result.remove(item)
        elif item in result: # 삭제할 때
            result.remove(item)
            if impossible(result):
                result.add(item)
    answer = map(list, result)

    return sorted(answer, key = lambda x : (x[0], x[1], x[2]))

In [315]:
solution(n,build_frame)

[[0, 0, 0], [0, 1, 1], [1, 1, 1], [2, 1, 1], [3, 1, 1], [4, 0, 0]]

## 외벽 점검

In [759]:
n = 12
weak = [1, 5, 6, 10]
dist = [1, 2, 3, 4]

In [760]:
def solution(n, weak, dist):
    weak_reverse = [element+n for element in weak]
    weak = weak + weak_reverse

    dist = sorted(dist, reverse=True)

    friends = 0
    for dist_element in dist:
        array = []
        total_count = 0
        for i in range(0, n*2-dist_element):
            start, end = i, i+dist_element
            count = 0
            to_remove = []
            for weak_element in weak:
                if start <= weak_element <= end:
                    count += 1
                    to_remove.append(weak_element)
                    if weak_element+12 < n*2:
                        to_remove.append(weak_element+12)
                    else:
                        to_remove.append(weak_element-12)

            weak_copy = weak[:]
            for item in to_remove:
                if item in weak_copy:
                    weak_copy.remove(item)

            array.append([count, weak_copy[0:len(weak_copy)//2]])

        array.sort(key = lambda x:x[0], reverse=True)

        friends += 1
        if array[0][1] != []:
            array.sort(key = lambda x:x[1][1]-x[1][0], reverse=True)
        else:
            return friends
        
        final_remover = []
        for item in array[0][1]:
            if item in weak:
                final_remover.append(item)
            if item+12 in weak:
                final_remover.append(item+12)
            if item-12 in weak:
                final_remover.append(item-12)
        for remover in final_remover:
            weak.remove(remover)


    return friends

In [761]:
solution(n, weak, dist)

2

In [783]:
#다른 사람 풀이 1
from itertools import permutations
def solution(n,weak,dist):
    L = len(weak)
    cand = []
    weak_point = weak + [w+n for w in weak] #선형으로 변경
    for i, start in enumerate(weak):
        for friends in permutations(dist):
            count = 1
            position = start
            # 친구 조합 배치
            for friend in friends:
                position += friend
                # 끝 포인트까지 도달 못했을 때
                if position < weak_point[i+L-1]:
                    count += 1 # 친구 더 투입
                    # 현재 위치보다 멀리 있는 취약지점 중 가장 가까운 위치로
                    position = [w for w in weak_point[i+1:i+L] if w > position][0]
                else: #끝 포인트까지 도달
                    cand.append(count)
                    break
    return min(cand) if cand else -1
    

In [784]:
solution(n, weak, dist)

2

In [803]:
#다른 사람 풀이 2
from collections import deque

def solution(n, weak, dist):
    dist.sort(reverse=True)
    q = deque([weak])
    visited = set()
    visited.add(tuple(weak))

    for i in range(len(dist)):
        d = dist[i]
        for _ in range(len(q)):
            current = q.popleft()
            for p in current:
                l = p
                r = (p + d) % n
                if l < r:
                    temp = tuple(filter(lambda x: x < l or x > r, current))

                else:
                    temp = tuple(filter(lambda x: x < l and x > r, current))
                if len(temp) == 0:
                    return (i + 1)
                elif temp not in visited:
                    visited.add(temp)
                    q.append(list(temp))
    return -1


In [804]:
solution(n, weak, dist)

2

## 블록 이동하기

In [810]:
#input
board = [[0, 0, 0, 1, 1],[0, 0, 0, 1, 0],[0, 1, 0, 1, 1],[1, 1, 0, 0, 1],[0, 0, 0, 0, 0]]

In [835]:
from collections import deque

def can_move(cur1, cur2, new_board):
    Y, X = 0, 1
    cand = []
    # 평행이동
    DELTAS = [(-1, 0), (1, 0), (0, 1), (0, -1)]
    for dy, dx in DELTAS:
        nxt1 = (cur1[Y] + dy, cur1[X] + dx)
        nxt2 = (cur2[Y] + dy, cur2[X] + dx)
        if new_board[nxt1[Y]][nxt1[X]] == 0 and new_board[nxt2[Y]][nxt2[X]] == 0:
            cand.append((nxt1, nxt2))
    # 회전
    if cur1[Y] == cur2[Y]: # 가로방향 일 때
        UP, DOWN = -1, 1
        for d in [UP, DOWN]:
            if new_board[cur1[Y]+d][cur1[X]] == 0 and new_board[cur2[Y]+d][cur2[X]] == 0:
                cand.append((cur1, (cur1[Y]+d, cur1[X])))
                cand.append((cur2, (cur2[Y]+d, cur2[X])))
    else: # 세로 방향 일 때
        LEFT, RIGHT = -1, 1
        for d in [LEFT, RIGHT]:
            if new_board[cur1[Y]][cur1[X]+d] == 0 and new_board[cur2[Y]][cur2[X]+d] == 0:
                cand.append(((cur1[Y], cur1[X]+d), cur1))
                cand.append(((cur2[Y], cur2[X]+d), cur2))
    return cand

def solution(board):
    # board 외벽 둘러싸기
    N = len(board)
    new_board = [[1] * (N+2) for _ in range(N+2)]
    for i in range(N):
        for j in range(N):
            new_board[i+1][j+1] = board[i][j]
    # 현재 좌표 위치 큐 삽입, 확인용 set
    que = deque([((1, 1), (1, 2), 0)])
    confirm = set([((1, 1), (1, 2))])

    while que:
        cur1, cur2, count = que.popleft()
        if cur1 == (N, N) or cur2 == (N, N):
            return count
        for nxt in can_move(cur1, cur2, new_board):
            if nxt not in confirm:
                que.append((*nxt, count+1))
                confirm.add(nxt)

In [836]:
solution(board)

[[1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]
[[1, 1, 1, 1, 1, 1, 1], [1, 0, 0, 0, 1, 1, 1], [1, 0, 0, 0, 1, 0, 1], [1, 0, 1, 0, 1, 1, 1], [1, 1, 1, 0, 0, 1, 1], [1, 0, 0, 0, 0, 0, 1], [1, 1, 1, 1, 1, 1, 1]]


7